Don't fail on null primitives
A vehicle request returned '"postion":{"lat":null,"lng":null}' which caused
Jackson to bail out with an exception:

> MismatchedInputException: Cannot map `null` into type `double`